version: '3'
services:
  magicmirror:
    container_name: magicmirror
    image: bastilimbach/docker-magicmirror
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${WORKING_DIRECTORY}/config:/opt/magic_mirror/config
      - ${WORKING_DIRECTORY}/modules:/opt/magic_mirror/modules
    ports:
      - 8888:8080
