version: '3'
services:
  magicmirror:
    container_name: magicmirror
    image: bastilimbach/docker-magicmirror
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/projects/magicmirror/config:/opt/magic_mirror/config
      - ~/projects/magicmirror/modules:/opt/magic_mirror/modules
    ports:
      - 8888:8080
